### ISSUE TITLE
Add Nelson

### ISSUE THREAD

**Issue by Noki** [bluedigits/iota-node#22]
Hi @bluedigits !

Your image is great and has by far the most pulls of all iota-node image on docker hub but I bet a lot of people give up when it comes to finding neighbors. ;-)

Is there any chance that you add Nelson (https://github.com/SemkoDev/nelson.cli)?

Best regards
Tobias

**Comment by bluedigits** [comment]
Hey @Noki 

Glad to hear :) Jep, I'm already working on integrating Nelson!

Best,
Merlin

**Comment by bluedigits** [comment]
Hey @Noki 

Since it basically destroys all advantages from containerization when running multiple processes within a single container I just added information on how to run the IRI Docker container together with another Nelson container to our README file: https://github.com/bluedigits/iota-node/blob/master/README.md

Does this suit your needs?

Best,
Merlin

**Comment by Noki** [comment]
Hi @bluedigits ,

I think this is fine. Thank you.

Best regards
Tobias
